add_help_cmd: True
allow_abbrev: False
print_help: True
page_help: True
description: Query2vec.

anchors:
    main: &MAIN
        help:
            short: h
            action: help
            default: __SUPPRESS__
            help: Show this help message and exit.
        conf_file:
            help: 'Configuration file (default: __DEFAULT__).'
            default: __FILE__/conf/config.yml
        logdir:
            help: 'Log directory (default: __DEFAULT__).'
            default: __FILE__/data/logs
        loglevel:
            choices: [debug, info, warn, error]
            type: LoggerLevel
            default: info
            help: 'Log level on console (default: __DEFAULT__).'

subparsers:
    train:
        description: >
            train the query2vec model
        help: TRAIN the query2vec model.
        add_help: False
        print_help: True
        groups:
            - title: Common options
              options: *MAIN
            - title: Vocabulary options
              options:
                special_words:
                    help: special words to indicate the unknown words, sentence start tag and sentence end tag
                    default:
                        <unk>: 1
                        <s>: 2
                        </s>: 3
                vocabulary_path:
                    default: __FILE__/data/vocabulary/top.pkl
                    help: |
                        path for source vocabulary
                        'source_vocab_path(default: __DEFAULT__).'
            - title: Data set
              options:
                train_source_path:
                    default: __FILE__/data/train_corpus/train.enc
                    help: |
                        path for train source(encoder) data
                        'train_source_path(default: __DEFAULT__).'
                train_target_path:
                    default: __FILE__/data/train_corpus/train.dec
                    help: |
                        path for train target(decoder) data
                        'train_target_path(default: __DEFAULT__).'

            - title: Model parameter
              options:
                buckets:
                    default:
                        - !!python/tuple [3, 10]
                        - !!python/tuple [3, 20]
                        - !!python/tuple [5, 20]
                        - !!python/tuple [7, 30]
                    help:
                        'use a number of buckets and pad to the closest one for efficiency.(default: __DEFAULT__)'

                s_hidden_unit:
                    type: int
                    default: 512
                    help:
                        'Configuration file (default: __DEFAULT__).'
                s_embed_size:
                    type: int
                    default: 150
                    help:
                        'Configuration file (default: __DEFAULT__).'
                s_layer_num:
                    type: int
                    default: 2
                    help: number of layers in the neural network, required by some networks such as resnet
                t_layer_num:
                    type: int
                    default: 2
                    help:
                        'Configuration file (default: __DEFAULT__).'
                t_hidden_unit:
                    type: int
                    default: 512
                    help:
                        'Configuration file (default: __DEFAULT__).'
                t_embed_size:
                    type: int
                    default: 150
                    help: |
                        'Configuration file (default: __DEFAULT__).'
                t_label_num:
                    type: int
                    default: 2
                    help:
                        'Configuration file (default: __DEFAULT__).'
                model_prefix:
                    default: __FILE__/data/model/query2vec
                    help: Batch size to use during training.
            - title: Training parameter
              options:
                batch_size:
                    type: int
                    default: 128
                    help: Batch size to use during training.
                device_model:
                    default: cpu
                    help:
                        'Configuration file (default: __DEFAULT__).'
                devices:
                    default: "0"
                    help:
                        'Configuration file (default: __DEFAULT__).'
                kv_store:
                    default: local
                    help:
                        'Configuration file (default: __DEFAULT__).'
                train_max_samples:
                    type: Integer
                    default: "inf"
                    help:
                        'Configuration file (default: __DEFAULT__).'
                show_every_x_batch:
                    type: int
                    default: 2
                    help: show progress for every x batches
                eval_per_x_batch:
                    type: int
                    default: 400
                    help:
                        'Configuration file (default: __DEFAULT__).'
                eval_start_epoch:
                    type: int
                    default: 4
                    help:
                        'Configuration file (default: __DEFAULT__).'
                learning_rate:
                    type: float
                    default: 1.0
                    help:
                        'Configuration file (default: __DEFAULT__).'
                s_dropout:
                    type: float
                    default: 0.5
                    help:
                        'Configuration file (default: __DEFAULT__).'
                t_dropout:
                    type: float
                    default: 0.5
                    help:
                        'Configuration file (default: __DEFAULT__).'
                num_epoch:
                    type: Integer
                    default: 65535
                    help: number of training epochs.
                optimizer:
                    default: sgd
                    help: the optimizer type
                momentum:
                    type: float
                    default: 0.9
                    help: momentum for sgd
                wd:
                    type: float
                    default: 0.0001
                    help: weight decay for sgd
                lr_factor:
                    type: float
                    help: the ratio to reduce lr on each step
                lr:
                    type: float
                    default: 0.05
                    help: initial learning rate
                load_epoch:
                    type: int
                    help: load the model on an epoch using the model-prefix
                num_examples:
                    type: int
                    default: 65525
                    help: number of training example
            - title: Mxnet parameter
              options:
                monitor_interval:
                    type: int
                    default: 0
                    help: log network parameters every N iters if larger than 0
            - title: Arguments
              args:
                src_host:
                    metavar: MODEL
                    help: Hypervisor source.

    test:
        description: >
            train the query2vec model
        help: TRAIN the query2vec model.
        add_help: False
        print_help: True
        groups:
            - title: Common options
              options: *MAIN
            - title: Optional Vocabulary options
              options:
                special_words:
                    default:
                        "Fsdfsf"
            - title: Arguments
              args:
                src_host:
                    metavar: MODEL
                    help: Hypervisor source.
    vocab:
        description: >
            vocabulary generator
        help: create vocabulary
        add_help: False
        print_help: True
        groups:
            - title: Common options
              options: *MAIN
            - title: Vocabulary options
              options:
                special_words:
                    default:
                        <unk>: 1
                        <s>: 2
                        </s>: 3
                    help: special words to indicate the unknown words, sentence start tag and sentence end tag. (__DEFAULT__)
                most_commond_words_num:
                    default: 40000
                    type: int
                    help: the number of the most common words in vocabulary
                overwrite:
                    action: store_true
                    help: |
                        overwrite earlier created files, also forces the
                        program not to reuse count files
            - title: Arguments
              args:
                files:
                    nargs: '+'
                    help: the corpus input files
                vocab_file_path:
                    help: the file with all the unique words and related frequency
                most_commond_words_file_path:
                    help: the file with the words which are the most command words in the corpus